# Generated by Django 5.0.6 on 2024-06-24 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('documento', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=20)),
                ('tipoDocumento', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('CE', 'CE'), ('CD', 'CD')], max_length=100)),
                ('nombre', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(default='', max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=250)),
                ('departamento', models.CharField(max_length=250)),
                ('salarioBasico', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Devengado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalDevengado', models.FloatField()),
                ('periodo', models.DateField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Deducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('periodo', models.DateField()),
                ('salud', models.FloatField()),
                ('pension', models.FloatField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='idEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.estadoempleado'),
        ),
        migrations.CreateModel(
            name='HorasExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadHoras', models.IntegerField()),
                ('total', models.FloatField()),
                ('codDevengado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.devengado')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('periodo', models.DateField()),
                ('codDeducciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.deducciones')),
                ('codDevengado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.devengado')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='NovedadDeducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('total', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('codDeducciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.deducciones')),
            ],
        ),
        migrations.CreateModel(
            name='NovedadDevengado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('total', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('codDevengado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.devengado')),
            ],
        ),
    ]
