# Generated by Django 5.0.6 on 2024-06-24 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='horasextras',
            old_name='cantidadHoras',
            new_name='diurna',
        ),
        migrations.RenameField(
            model_name='horasextras',
            old_name='documento',
            new_name='empleado',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='horasextras',
            name='total',
        ),
        migrations.AddField(
            model_name='horasextras',
            name='diurnaDominical',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horasextras',
            name='nocturna',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horasextras',
            name='nocturnaDominical',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horasextras',
            name='recargoDiurna',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horasextras',
            name='recargoNocturna',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horasextras',
            name='totalExtra',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.IntegerField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('jornadaLabaoral', models.IntegerField()),
                ('nivelRiesgo', models.CharField(max_length=100, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('idTipoContrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.tipocontrato')),
            ],
        ),
    ]
