# Generated by Django 5.0.6 on 2024-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_tipocontrato_rename_cantidadhoras_horasextras_diurna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horasextras',
            name='totalHoras',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
