# Generated by Django 5.0.6 on 2024-06-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_horasextras_totalhoras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='jornadaLabaoral',
            new_name='jornadaLaboral',
        ),
    ]
