# Generated by Django 5.0.6 on 2024-06-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_rename_jornadalabaoral_contrato_jornadalaboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horasextras',
            name='totalExtra',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='horasextras',
            name='totalHoras',
            field=models.IntegerField(editable=False),
        ),
    ]
