# Generated by Django 5.0.6 on 2024-06-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_alter_horasextras_totalextra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fechaFin',
            field=models.DateField(null=True),
        ),
    ]
