# Generated by Django 5.0.6 on 2024-06-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_alter_contrato_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
