# Generated by Django 5.0.6 on 2024-06-24 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0007_alter_contrato_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='empleado.empleado'),
        ),
    ]
