# Generated by Django 5.0.6 on 2024-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0009_alter_horasextras_totalextra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='periodoPago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
