# Generated by Django 5.0.6 on 2024-06-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0010_contrato_periodopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='periodoPago',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
