# Generated by Django 5.0.6 on 2024-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0011_alter_contrato_periodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='devengado',
            name='totalDevengadoIBC',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
