# Generated by Django 5.0.6 on 2024-06-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0012_devengado_totaldevengadoibc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='codDeducciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.deducciones'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='codDevengado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.devengado'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
