# Generated by Django 5.0.6 on 2024-06-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0013_alter_nomina_coddeducciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='periodo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
